
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ID LPAREN RPAREN COLON SEMI MARKERSPRESENT NUM0 NUM2 PICKMARKER NUM4 NUM5 NUM6 NUM1 NUM8 NUM9 NUM10 MOVE NUM12 NUM13 NUM14 NUM15 TURNRIGHT NUM17 NUM18 NUM3 NOMARKERSPRESENT PUTMARKER LEFTISCLEAR IF TURNLEFT NUM7 FRONTISCLEAR IFELSE REPEAT RUN ELSE NUM11 RIGHTISCLEAR NOT NUM16 WHILE NUM19 DEFprog : DEF RUN stmtstmt : WHILE LPAREN cond RPAREN COLON \n    cond : FRONTISCLEAR LPAREN RPAREN\n            | LEFTISCLEAR LPAREN RPAREN\n            | RIGHTISCLEAR LPAREN RPAREN\n            | MARKERSPRESENT LPAREN RPAREN \n            | NOMARKERSPRESENT LPAREN RPAREN\n            | NOT cond\n    cond : MOVE LPAREN RPAREN\n            | TURNRIGHT LPAREN RPAREN\n            | TURNLEFT LPAREN RPAREN\n            | PICKMARKER LPAREN RPAREN\n            | PUTMARKER LPAREN RPAREN\n    cste : NUM0\n            | NUM1\n            | NUM2\n            | NUM3\n            | NUM4\n            | NUM5\n            | NUM6\n            | NUM7\n            | NUM8\n            | NUM9\n            | NUM10\n            | NUM11\n            | NUM12\n            | NUM13\n            | NUM14\n            | NUM15\n            | NUM16\n            | NUM17\n            | NUM18\n            | NUM19\n    '
    
_lr_action_items = {'MARKERSPRESENT':([6,17,],[7,7,]),'FRONTISCLEAR':([6,17,],[13,13,]),'PICKMARKER':([6,17,],[15,15,]),'RUN':([2,],[3,]),'RPAREN':([18,19,20,21,22,23,24,25,26,27,28,29,31,32,33,34,35,36,37,38,39,40,],[30,31,32,33,34,35,36,37,38,39,40,-8,-6,-10,-9,-13,-11,-7,-3,-5,-12,-4,]),'TURNLEFT':([6,17,],[11,11,]),'MOVE':([6,17,],[9,9,]),'TURNRIGHT':([6,17,],[8,8,]),'RIGHTISCLEAR':([6,17,],[14,14,]),'WHILE':([3,],[5,]),'COLON':([30,],[41,]),'LPAREN':([5,7,8,9,10,11,12,13,14,15,16,],[6,19,20,21,22,23,24,25,26,27,28,]),'NOMARKERSPRESENT':([6,17,],[12,12,]),'PUTMARKER':([6,17,],[10,10,]),'LEFTISCLEAR':([6,17,],[16,16,]),'NOT':([6,17,],[17,17,]),'DEF':([0,],[2,]),'$end':([1,4,41,],[0,-1,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'prog':([0,],[1,]),'cond':([6,17,],[18,29,]),'stmt':([3,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> prog","S'",1,None,None,None),
  ('prog -> DEF RUN stmt','prog',3,'p_prog','parser.py',7),
  ('stmt -> WHILE LPAREN cond RPAREN COLON','stmt',5,'p_stmt','parser.py',10),
  ('cond -> FRONTISCLEAR LPAREN RPAREN','cond',3,'p_cond','parser.py',14),
  ('cond -> LEFTISCLEAR LPAREN RPAREN','cond',3,'p_cond','parser.py',15),
  ('cond -> RIGHTISCLEAR LPAREN RPAREN','cond',3,'p_cond','parser.py',16),
  ('cond -> MARKERSPRESENT LPAREN RPAREN','cond',3,'p_cond','parser.py',17),
  ('cond -> NOMARKERSPRESENT LPAREN RPAREN','cond',3,'p_cond','parser.py',18),
  ('cond -> NOT cond','cond',2,'p_cond','parser.py',19),
  ('cond -> MOVE LPAREN RPAREN','cond',3,'p_action','parser.py',23),
  ('cond -> TURNRIGHT LPAREN RPAREN','cond',3,'p_action','parser.py',24),
  ('cond -> TURNLEFT LPAREN RPAREN','cond',3,'p_action','parser.py',25),
  ('cond -> PICKMARKER LPAREN RPAREN','cond',3,'p_action','parser.py',26),
  ('cond -> PUTMARKER LPAREN RPAREN','cond',3,'p_action','parser.py',27),
  ('cste -> NUM0','cste',1,'p_cste','parser.py',31),
  ('cste -> NUM1','cste',1,'p_cste','parser.py',32),
  ('cste -> NUM2','cste',1,'p_cste','parser.py',33),
  ('cste -> NUM3','cste',1,'p_cste','parser.py',34),
  ('cste -> NUM4','cste',1,'p_cste','parser.py',35),
  ('cste -> NUM5','cste',1,'p_cste','parser.py',36),
  ('cste -> NUM6','cste',1,'p_cste','parser.py',37),
  ('cste -> NUM7','cste',1,'p_cste','parser.py',38),
  ('cste -> NUM8','cste',1,'p_cste','parser.py',39),
  ('cste -> NUM9','cste',1,'p_cste','parser.py',40),
  ('cste -> NUM10','cste',1,'p_cste','parser.py',41),
  ('cste -> NUM11','cste',1,'p_cste','parser.py',42),
  ('cste -> NUM12','cste',1,'p_cste','parser.py',43),
  ('cste -> NUM13','cste',1,'p_cste','parser.py',44),
  ('cste -> NUM14','cste',1,'p_cste','parser.py',45),
  ('cste -> NUM15','cste',1,'p_cste','parser.py',46),
  ('cste -> NUM16','cste',1,'p_cste','parser.py',47),
  ('cste -> NUM17','cste',1,'p_cste','parser.py',48),
  ('cste -> NUM18','cste',1,'p_cste','parser.py',49),
  ('cste -> NUM19','cste',1,'p_cste','parser.py',50),
]
